services:
  nginx:
    image: nginx:alpine
    container_name: site-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./index.html:/usr/share/nginx/index.html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot \
      --webroot-path=/var/www/certbot \
      -d *.borsch-krd.ru \
      --email just.hornet228@gmail.com \
      --agree-tos \
      --non-interactive
